### ISSUE TITLE
TelnetD app refers to Telnet as SSD

### ISSUE THREAD

**Issue by canllaith** [djware/TrimUITools#3]
Gday,

I apologies for the typo in the issue title - should read SSH and not SSD.

Thank you very much for your work developing apps for the TrimUI. I wanted to point out an error in the readme.md - Telnet is not the same thing as SSH. Telnet is unencrypted and known to be insecure, whereas SSH is pretty much the gold standard for secure access.

The TrimUI does not have SSH binaries so it's understandable that you would need to go with Telnet, but perhaps the documentation can be updated to reflect the above. Happy to submit a pull request.

**Comment by djware** [comment]
Thanks for the call out, Canllaith. I did forget to update that. Doing so now. Thanks again.
